[build]
  command = "pip install -r requirements.txt"
  publish = "static"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Cache-Control = "public, max-age=3600"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["pandas", "openpyxl"]
  included_files = ["requirements.txt", "**/*.xlsx"]

[build.environment]
  PYTHON_VERSION = "3.12"

[dev]
  command = "netlify dev"
  targetPort = 8000