[build]
  command = "pip install -r requirements.txt"
  publish = "static"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external = ["mangum"]

[dev]
  command = "uvicorn main:app --host 0.0.0.0 --port 8000"
  targetPort = 8000