[build]
  command = "pip install -r requirements.txt && python main.py"
  publish = "public"

[functions]

    [functions.include]
    external_node_modules = [
      "module-one",
      "module-two"
    ]